<?php

use Drupal\views\ViewExecutable;
  
/**
* Implements hook_views_pre_render().
*/
function testimonial_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'testimonials')) {
    $view->element['#attached']['library'][] = 'testimonial/testimonial-view';
  }
}

/**
 * Implements hook_theme().
 */
function testimonial_theme($existing, $type, $theme, $path) {
  return [
    'node__testimonial' => [
      'template' => 'node--testimonial',
      'base hook' => 'node'
    ],
    'views_view_fields__testimonials__testimonials_page' => [
      'template' => 'testimonials_page_fields',
      'base hook' => 'view fields',
    ],
    'views_view_fields__testimonials__sb_slide_block' => [
      'template' => 'sb_slide_block_fields',
      'base hook' => 'view fields',
    ],
    'views_view_fields__testimonials__sb_block_ref_block' => [
      'template' => 'sb_block_refresh_fields',
      'base hook' => 'view fields',
    ],
    'views_view_fields__testimonials__fw_slide_block' => [
      'template' => 'fw_slide_block_fields',
      'base hook' => 'view fields',
    ],
    'views_view_fields__testimonials__fw_refresh_block' => [
      'template' => 'fw_block_refresh_fields',
      'base hook' => 'view fields',
    ],
  ];

}

function testimonial_preprocess_views_view_fields(&$variables) {
  
  if($variables['view']->id() == 'testimonials') {

    $fields = $variables['fields'];
    $variables['view_node_link'] = $variables['row']->_entity->toUrl()->toString();

    foreach($fields as $fieldName => $field) {

      if($variables['row']->_entity->$fieldName !== null && 
        !empty($variables['row']->_entity->$fieldName->getValue()[0]['value'])) {

        $variables[$fieldName] = $field->content;

      }

    }

  }
}
