<?php

use Drupal\views\ViewExecutable;
  
/**
* Implements hook_views_pre_render().
*/
function testimonial_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'testimonials')) {
    $view->element['#attached']['library'][] = 'testimonial/testimonial-view';
  }
}

/**
 * Implements hook_theme().
 */
function testimonial_theme($existing, $type, $theme, $path) {
  return [
    'node__testimonial' => [
      'template' => 'node--testimonial',
      'base hook' => 'node'
    ],
  ];

}
