<?php
/**
 * @file
 * testimonials.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function testimonials_views_default_views() {
  $export = array();

  $view = new view();
  $view->name = 'tribute_testimonials';
  $view->description = 'Displays for Testimonials content type. Includes standard block, rotating block, and a page display.';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'Testimonials';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Testimonials';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['query_comment'] = FALSE;
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* Field: Content: Snippet */
  $handler->display->display_options['fields']['field_snippet']['id'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['table'] = 'field_data_field_snippet';
  $handler->display->display_options['fields']['field_snippet']['field'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['label'] = '';
  $handler->display->display_options['fields']['field_snippet']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_snippet']['alter']['text'] = '<div class="testimonial-wrapper">
<div class="inner">
<div class="testimonial-snippet">[field_snippet]</div>
<div class="testimonial-name">[title]</div>
<div class="testimonial-title">[field_business_title]</div>
<div class=
</div></div>';
  $handler->display->display_options['fields']['field_snippet']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Content: Business Title */
  $handler->display->display_options['fields']['field_business_title']['id'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['table'] = 'field_data_field_business_title';
  $handler->display->display_options['fields']['field_business_title']['field'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['label'] = '';
  $handler->display->display_options['fields']['field_business_title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_title']['element_label_colon'] = FALSE;
  /* Field: Content: Business Name */
  $handler->display->display_options['fields']['field_business_name']['id'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['table'] = 'field_data_field_business_name';
  $handler->display->display_options['fields']['field_business_name']['field'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['label'] = '';
  $handler->display->display_options['fields']['field_business_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_name']['element_label_colon'] = FALSE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<div class="testimonial__body">[body]</div>
<div class="testimonial__info">
  <div class="testimonial__title">[title]</div>
  <div class="testimonial__business-title">[field_business_title]</div>
  <div class="testimonial__business-name">[field_business_name]</div>
</div>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 0;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'testimonials' => 'testimonials',
  );

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['header'] = FALSE;
  /* Header: Global: Text area */
  $handler->display->display_options['header']['area']['id'] = 'area';
  $handler->display->display_options['header']['area']['table'] = 'views';
  $handler->display->display_options['header']['area']['field'] = 'area';
  $handler->display->display_options['header']['area']['content'] = '<div><div class="define">You can choose to have a simple page of testimonials. A simple page would require you to edit that page each time you receive a new testimonial and would not provide a sidebar with rotating testimonials. This testimonials feature automatically formats a page with all your testimonials and allows you to have them in a rotating sidebar block that shows up throughout your website. This is optional for our websites.</div></div>

<style>
.define {
background:transparent url(\'/files/imce/1px-darken-3.png\');
padding: 10px;
border: 1px dotted #aaa;
}
.dark-region .define {
background:transparent url(\'/files/imce/1px-lighten-3.png\');
border-color: #777;
}
</style>';
  $handler->display->display_options['header']['area']['format'] = 'full_html';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Snippet */
  $handler->display->display_options['fields']['field_snippet']['id'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['table'] = 'field_data_field_snippet';
  $handler->display->display_options['fields']['field_snippet']['field'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['label'] = '';
  $handler->display->display_options['fields']['field_snippet']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_snippet']['alter']['text'] = '<div class="testimonial-wrapper">
<div class="inner">
<div class="testimonial-snippet">[field_snippet]</div>
<div class="testimonial-name">[title]</div>
<div class="testimonial-title">[field_business_title]</div>
<div class=
</div></div>';
  $handler->display->display_options['fields']['field_snippet']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Content: Business Title */
  $handler->display->display_options['fields']['field_business_title']['id'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['table'] = 'field_data_field_business_title';
  $handler->display->display_options['fields']['field_business_title']['field'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['label'] = '';
  $handler->display->display_options['fields']['field_business_title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_title']['element_label_colon'] = FALSE;
  /* Field: Content: Business Name */
  $handler->display->display_options['fields']['field_business_name']['id'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['table'] = 'field_data_field_business_name';
  $handler->display->display_options['fields']['field_business_name']['field'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['label'] = '';
  $handler->display->display_options['fields']['field_business_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_name']['element_label_colon'] = FALSE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<div class="testimonial__body">[field_snippet]</div>
<div class="testimonial__info">
  <div class="testimonial__title">[title]</div>
  <div class="testimonial__business-title">[field_business_title]</div>
  <div class="testimonial__business-name">&nbsp; [field_business_name]</div>
</div>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['path'] = 'testimonials';

  /* Display: Testimonials Block */
  $handler = $view->new_display('block', 'Testimonials Block', 'block_1');
  $handler->display->display_options['display_description'] = 'Displays on internal pages only';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Snippet */
  $handler->display->display_options['fields']['field_snippet']['id'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['table'] = 'field_data_field_snippet';
  $handler->display->display_options['fields']['field_snippet']['field'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['label'] = '';
  $handler->display->display_options['fields']['field_snippet']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_snippet']['alter']['text'] = '<div class="testimonial-wrapper">
<div class="inner">
<div class="testimonial-snippet">[field_snippet]</div>
<div class="testimonial-name">[title]</div>
<div class="testimonial-title">[field_business_title]</div>
<div class=
</div></div>';
  $handler->display->display_options['fields']['field_snippet']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Content: Business Title */
  $handler->display->display_options['fields']['field_business_title']['id'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['table'] = 'field_data_field_business_title';
  $handler->display->display_options['fields']['field_business_title']['field'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['label'] = '';
  $handler->display->display_options['fields']['field_business_title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_business_title']['alter']['text'] = '[field_business_title], ';
  $handler->display->display_options['fields']['field_business_title']['element_label_colon'] = FALSE;
  /* Field: Content: Business Name */
  $handler->display->display_options['fields']['field_business_name']['id'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['table'] = 'field_data_field_business_name';
  $handler->display->display_options['fields']['field_business_name']['field'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['label'] = '';
  $handler->display->display_options['fields']['field_business_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_name']['element_label_colon'] = FALSE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<div class="testimonial__body">[field_snippet]</div>
<div class="testimonial__info">
  <div class="testimonial__title">[title]</div>
  <div class="testimonial__business-title">[field_business_title]</div>
  <div class="testimonial__business-name">&nbsp; [field_business_name]</div>
</div>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['defaults']['sorts'] = FALSE;
  /* Sort criterion: Global: Random */
  $handler->display->display_options['sorts']['random']['id'] = 'random';
  $handler->display->display_options['sorts']['random']['table'] = 'views';
  $handler->display->display_options['sorts']['random']['field'] = 'random';
  $handler->display->display_options['block_description'] = 'Testimonials Internal';

  /* Display: Rotating Testimonials Block */
  $handler = $view->new_display('block', 'Rotating Testimonials Block', 'block_2');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'jcarousel';
  $handler->display->display_options['style_options']['wrap'] = 'circular';
  $handler->display->display_options['style_options']['skin'] = '';
  $handler->display->display_options['style_options']['visible'] = '1';
  $handler->display->display_options['style_options']['auto'] = '5';
  $handler->display->display_options['style_options']['autoPause'] = 1;
  $handler->display->display_options['style_options']['easing'] = '';
  $handler->display->display_options['style_options']['vertical'] = 0;
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Snippet */
  $handler->display->display_options['fields']['field_snippet']['id'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['table'] = 'field_data_field_snippet';
  $handler->display->display_options['fields']['field_snippet']['field'] = 'field_snippet';
  $handler->display->display_options['fields']['field_snippet']['label'] = '';
  $handler->display->display_options['fields']['field_snippet']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_snippet']['alter']['text'] = '<div class="testimonial-wrapper">
<div class="inner">
<div class="testimonial-snippet">[field_snippet]</div>
<div class="testimonial-name">[title]</div>
<div class="testimonial-title">[field_business_title]</div>
<div class=
</div></div>';
  $handler->display->display_options['fields']['field_snippet']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Content: Business Title */
  $handler->display->display_options['fields']['field_business_title']['id'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['table'] = 'field_data_field_business_title';
  $handler->display->display_options['fields']['field_business_title']['field'] = 'field_business_title';
  $handler->display->display_options['fields']['field_business_title']['label'] = '';
  $handler->display->display_options['fields']['field_business_title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_business_title']['alter']['text'] = '[field_business_title], ';
  $handler->display->display_options['fields']['field_business_title']['element_label_colon'] = FALSE;
  /* Field: Content: Business Name */
  $handler->display->display_options['fields']['field_business_name']['id'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['table'] = 'field_data_field_business_name';
  $handler->display->display_options['fields']['field_business_name']['field'] = 'field_business_name';
  $handler->display->display_options['fields']['field_business_name']['label'] = '';
  $handler->display->display_options['fields']['field_business_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_business_name']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_business_name']['alter']['text'] = '[field_business_name]';
  $handler->display->display_options['fields']['field_business_name']['element_label_colon'] = FALSE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<div class="testimonial__body">[field_snippet]</div>
<div class="testimonial__info">
  <div class="testimonial__title">[title]</div>
  <div class="testimonial__business-title">[field_business_title]</div>
  <div class="testimonial__business-name">[field_business_name]</div>
</div>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $export['tribute_testimonials'] = $view;

  return $export;
}
